sudo: required
services:
  - docker

before_install:
  - docker build -t judsondouglas/docker-react-three -f Dockerfile.dev .

script:
  - docker run -e CI=true judsondouglas/docker-react-three npm run test